let useFiles = [
"./Mixed_Fx_Sounds/90 Realm.wav",
"./Mixed_Fx_Sounds/91 Twisted.wav",
"./Mixed_Fx_Sounds/92 Ghosts.wav",
"./Noises/Analogue Hiss Lo Boost.aif",
"./Noises/Analogue Hiss Lo Cut.aif",
"./Noises/Analogue Hiss Mid Boost.aif",
"./Noises/Crackle Pops.aif",
"./Noises/Crunchy Crackle.aif",
"./Noises/Fake Vinyl 1.aif",
"./Noises/Fake Vinyl 2.aif",
"./Noises/FizzPop.aif",
"./Noises/FizzPopper2.aif",
"./ORGANIC_LPS_135_BPM/ZS_Organic_01_Louis_135.wav",
"./ORGANIC_LPS_135_BPM/ZS_Organic_02_Water_Drops_135.wav",
"./ORGANIC_LPS_135_BPM/ZS_Organic_03_Hammer_135.wav",
"./ORGANIC_LPS_135_BPM/ZS_Organic_04_Drips_in_the_House_135.wav",
"./ORGANIC_LPS_135_BPM/ZS_Organic_05_Juve_135.wav",
"./ORGANIC_LPS_135_BPM/ZS_Organic_06_Birdsong_135.wav",
"./ORGANIC_LPS_135_BPM/ZS_Organic_07_Bardi_135.wav",
"./ORGANIC_LPS_135_BPM/ZS_Organic_08_Broken_Glass_135.wav",
"./ORGANIC_LPS_135_BPM/ZS_Organic_09_Back_Yard_Rain_135.wav",
"./ORGANIC_LPS_135_BPM/ZS_Organic_10_Bubbling_135.wav",
"./ORGANIC_LPS_90_BPM/TDDC_Organic_01_Distorted_Drip_Sirens_90.wav",
"./ORGANIC_LPS_90_BPM/TDDC_Organic_02_Water_Drops_90.wav",
"./ORGANIC_LPS_90_BPM/TDDC_Organic_03_Italian_Animals_90.wav",
"./ORGANIC_LPS_90_BPM/TDDC_Organic_04_Rain_and_Road_Noise_90.wav",
"./ORGANIC_LPS_90_BPM/TDDC_Organic_06_Rain_and_Drain_90.wav",
"./ORGANIC_LPS_90_BPM/TDDC_Organic_06_Thunder_Storm_90.wav",
"./ORGANIC_LPS_90_BPM/TDDC_Organic_07_Seagulls_90.wav",
"./ORGANIC_LPS_90_BPM/TDDC_Organic_08_Street_Echoes_90.wav",
"./ORGANIC_LPS_90_BPM/TDDC_Organic_09_Surf_90.wav",
"./ORGANIC_LPS_90_BPM/TDDC_Organic_10_Street_Life_90.wav",
"./S7_recordings/S7_1.m4a",
"./S7_recordings/S7_2.m4a",
"./S7_recordings/S7_3.m4a",
"./S7_recordings/S7_4.m4a",
"./iPad_FX_Samples/sample_1-1.wav",
"./iPad_FX_Samples/sample_1-2.wav",
"./iPad_FX_Samples/sample_1-3.wav",
"./iPad_FX_Samples/sample_1-4.wav",
"./iPad_FX_Samples/sample_1-5.wav",
"./iPad_FX_Samples/sample_2-1.wav",
"./iPad_FX_Samples/sample_2-2.wav",
"./iPad_FX_Samples/sample_2-3.wav",
"./iPad_FX_Samples/sample_2-4.wav",
"./iPad_FX_Samples/sample_2-5.wav",
"./iPad_FX_Samples/sample_3-1.wav",
"./iPad_FX_Samples/sample_3-2.wav",
"./iPad_FX_Samples/sample_3-3.wav",
"./iPad_FX_Samples/sample_3-4.wav",
"./iPad_FX_Samples/sample_3-5.wav",
"./iPad_FX_Samples/sample_4-1.wav",
"./iPad_FX_Samples/sample_4-2.wav",
"./iPad_FX_Samples/sample_4-3.wav",
"./iPad_FX_Samples/sample_4-4.wav",
"./iPad_FX_Samples/sample_4-5.wav",
"./temp.js/*",
];
